// Generates supabase/migrations/0002_catalog_schema.sql with seed inserts
// derived from src/data/*.ts.
// Run with: node --experimental-strip-types scripts/generate-seed-sql.ts

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { CATEGORIES } from "../src/data/categories.ts";
import { PRODUCTS } from "../src/data/products.ts";
import { SHOPS } from "../src/data/shops.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

function sqlString(s: string | undefined | null): string {
  if (s == null) return "null";
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function sqlBool(b: boolean | undefined | null): string {
  return b ? "true" : "false";
}

function sqlNum(n: number | undefined | null): string {
  if (n == null) return "null";
  return String(n);
}

const categoryRows = CATEGORIES.map((c) => [
  sqlString(c.id),
  sqlString(c.slug),
  sqlString(c.name),
  sqlString(c.source),
  sqlString(c.icon),
  sqlString(c.emoji),
  sqlNum(c.itemsCount),
  sqlBool(c.highlight),
]);

const shopRows = SHOPS.map((s) => [
  sqlString(s.id),
  sqlString(s.slug),
  sqlString(s.name),
  sqlString(s.source),
  sqlString(s.description),
  sqlString(s.cover),
  sqlNum(s.rating),
  sqlBool(s.isOpen),
]);

const productRows = PRODUCTS.map((p) => [
  sqlString(p.id),
  sqlString(p.slug),
  sqlString(p.name),
  sqlString(p.source),
  sqlString(p.categoryId),
  p.shopId ? sqlString(p.shopId) : "null",
  sqlNum(p.price),
  p.oldPrice != null ? sqlNum(p.oldPrice) : "null",
  sqlString(p.unit),
  sqlString(p.image),
  sqlString(p.description),
  sqlBool(p.inStock),
  p.weight ? sqlString(p.weight) : "null",
  sqlBool(p.isWeekly),
]);

const shopsBlock = shopRows.length
  ? `insert into public.shops
  (id, slug, name, source, description, cover, rating, is_open)
values
${shopRows.map((row) => `  (${row.join(", ")})`).join(",\n")}
on conflict (id) do nothing;
`
  : `-- (no shops in seed — раздел «Лавки» наполняется через админку)
`;

const out = `-- AUTO-GENERATED by scripts/generate-seed-sql.ts
-- Catalog schema (categories, shops, products) + seed data from src/data/*.ts.
-- Run this in Supabase SQL Editor AFTER 0001_initial_schema.sql.

-- ──────────────────────────────────────────────────────────────────────────
-- Categories
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.categories (
  id           text primary key,
  slug         text not null unique,
  name         text not null,
  source       text not null check (source in ('market', 'shop', 'food')),
  icon         text not null,
  emoji        text not null,
  items_count  integer not null default 0,
  highlight    boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────────────────
-- Shops (магазины/лавки/кафе)
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.shops (
  id          text primary key,
  slug        text not null unique,
  name        text not null,
  source      text not null check (source in ('market', 'shop', 'food')),
  description text,
  cover       text,
  rating      double precision,
  is_open     boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────────────────
-- Products
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.products (
  id           text primary key,
  slug         text not null unique,
  name         text not null,
  source       text not null check (source in ('market', 'shop', 'food')),
  category_id  text not null references public.categories(id) on delete restrict,
  shop_id      text references public.shops(id) on delete set null,
  price        integer not null,
  old_price    integer,
  unit         text not null,
  image        text not null,
  description  text not null default '',
  in_stock     boolean not null default true,
  weight       text,
  is_weekly    boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_source_idx   on public.products(source);
create index if not exists products_weekly_idx   on public.products(is_weekly);

-- Auto-update updated_at on row update
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.touch_updated_at();

-- ──────────────────────────────────────────────────────────────────────────
-- Row Level Security: server-only access via service_role
-- ──────────────────────────────────────────────────────────────────────────
alter table public.categories enable row level security;
alter table public.shops      enable row level security;
alter table public.products   enable row level security;

-- ──────────────────────────────────────────────────────────────────────────
-- Seed: categories
-- ──────────────────────────────────────────────────────────────────────────
insert into public.categories
  (id, slug, name, source, icon, emoji, items_count, highlight, sort_order)
values
${categoryRows
  .map((row, i) => `  (${row.join(", ")}, ${i})`)
  .join(",\n")}
on conflict (id) do nothing;

-- ──────────────────────────────────────────────────────────────────────────
-- Seed: shops
-- ──────────────────────────────────────────────────────────────────────────
${shopsBlock}
-- ──────────────────────────────────────────────────────────────────────────
-- Seed: products
-- ──────────────────────────────────────────────────────────────────────────
insert into public.products
  (id, slug, name, source, category_id, shop_id, price, old_price, unit,
   image, description, in_stock, weight, is_weekly, sort_order)
values
${productRows
  .map((row, i) => `  (${row.join(", ")}, ${i})`)
  .join(",\n")}
on conflict (id) do nothing;
`;

writeFileSync(
  resolve(repoRoot, "supabase/migrations/0002_catalog_schema.sql"),
  out
);
console.log(
  `Wrote 0002_catalog_schema.sql with ${CATEGORIES.length} categories, ${SHOPS.length} shops, ${PRODUCTS.length} products.`
);
