-- AUTO-GENERATED by scripts/generate-seed-sql.ts
-- Catalog schema (categories, shops, products) + seed data from src/data/*.ts.
-- Run this in Supabase SQL Editor AFTER 0001_initial_schema.sql.

-- ──────────────────────────────────────────────────────────────────────────
-- Categories
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.categories (
  id           text primary key,
  slug         text not null unique,
  name         text not null,
  source       text not null check (source in ('market', 'shop', 'food')),
  icon         text not null,
  emoji        text not null,
  items_count  integer not null default 0,
  highlight    boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────────────────
-- Shops (магазины/лавки/кафе)
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.shops (
  id          text primary key,
  slug        text not null unique,
  name        text not null,
  source      text not null check (source in ('market', 'shop', 'food')),
  description text,
  cover       text,
  rating      double precision,
  is_open     boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────────────────────
-- Products
-- ──────────────────────────────────────────────────────────────────────────
create table if not exists public.products (
  id           text primary key,
  slug         text not null unique,
  name         text not null,
  source       text not null check (source in ('market', 'shop', 'food')),
  category_id  text not null references public.categories(id) on delete restrict,
  shop_id      text references public.shops(id) on delete set null,
  price        integer not null,
  old_price    integer,
  unit         text not null,
  image        text not null,
  description  text not null default '',
  in_stock     boolean not null default true,
  weight       text,
  is_weekly    boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_source_idx   on public.products(source);
create index if not exists products_weekly_idx   on public.products(is_weekly);

-- Auto-update updated_at on row update
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.touch_updated_at();

-- ──────────────────────────────────────────────────────────────────────────
-- Row Level Security: server-only access via service_role
-- ──────────────────────────────────────────────────────────────────────────
alter table public.categories enable row level security;
alter table public.shops      enable row level security;
alter table public.products   enable row level security;

-- ──────────────────────────────────────────────────────────────────────────
-- Seed: categories
-- ──────────────────────────────────────────────────────────────────────────
insert into public.categories
  (id, slug, name, source, icon, emoji, items_count, highlight, sort_order)
values
  ('cat-veg', 'ovoshchi-frukty', 'Овощи и фрукты', 'market', 'carrot', '🥕', 24, true, 0),
  ('cat-meat', 'myaso', 'Мясо', 'market', 'drumstick', '🥩', 12, true, 1),
  ('cat-fish', 'ryba', 'Рыба и морепродукты', 'market', 'fish', '🐟', 9, false, 2),
  ('cat-dairy', 'molochka', 'Молочка и яйца', 'market', 'milk', '🥛', 11, false, 3),
  ('cat-bakery', 'khleb', 'Хлеб и выпечка', 'market', 'bread', '🥖', 8, false, 4),
  ('cat-cheese', 'syry-kolbasy', 'Сыры и колбасы', 'market', 'cheese', '🧀', 14, false, 5),
  ('cat-bakaleya', 'bakaleya', 'Бакалея', 'market', 'wheat', '🌾', 18, false, 6),
  ('cat-conserv', 'konservy', 'Консервация', 'market', 'can', '🥫', 7, false, 7),
  ('cat-frozen', 'zamorozka', 'Заморозка', 'market', 'snowflake', '❄️', 6, false, 8),
  ('cat-pickles', 'solenya', 'Соленья', 'market', 'jar', '🥒', 5, false, 9),
  ('cat-sweets', 'sladosti', 'Сладости', 'market', 'candy', '🍯', 9, false, 10),
  ('cat-oils', 'masla', 'Масла и соусы', 'market', 'bottle', '🫒', 6, false, 11),
  ('cat-spices', 'spetsii', 'Специи', 'market', 'spice', '🌶️', 10, false, 12),
  ('cat-tea', 'chay-kofe', 'Чай и кофе', 'market', 'tea', '☕', 8, false, 13),
  ('cat-pizza', 'pitstsa', 'Пицца', 'food', 'pizza', '🍕', 6, false, 14),
  ('cat-burger', 'burgery', 'Бургеры', 'food', 'burger', '🍔', 5, false, 15),
  ('cat-shashlik', 'shashlyk', 'Шашлык и хинкал', 'food', 'skewer', '🍢', 7, false, 16),
  ('cat-sushi', 'sushi', 'Суши и роллы', 'food', 'sushi', '🍣', 6, false, 17),
  ('cat-soup', 'supy', 'Супы', 'food', 'soup', '🍲', 4, false, 18),
  ('cat-salad', 'salaty', 'Салаты', 'food', 'salad', '🥗', 5, false, 19),
  ('cat-drinks', 'napitki', 'Напитки', 'food', 'cup', '🥤', 8, false, 20),
  ('cat-desserts', 'deserty', 'Десерты', 'food', 'cake', '🍰', 4, false, 21)
on conflict (id) do nothing;

-- ──────────────────────────────────────────────────────────────────────────
-- Seed: shops
-- ──────────────────────────────────────────────────────────────────────────
-- (no shops in seed — раздел «Лавки» наполняется через админку)

-- ──────────────────────────────────────────────────────────────────────────
-- Seed: products
-- ──────────────────────────────────────────────────────────────────────────
insert into public.products
  (id, slug, name, source, category_id, shop_id, price, old_price, unit,
   image, description, in_stock, weight, is_weekly, sort_order)
values
  ('p-tomato', 'pomidory-bychye-serdtse', 'Помидоры «Бычье сердце»', 'market', 'cat-veg', null, 220, null, 'кг', 'https://images.unsplash.com/photo-1768676124519-5b997fe3de4a?auto=format&fit=crop&w=600&q=70', 'Сочные мясистые помидоры сорта «Бычье сердце». Идеальны для салатов и горячих блюд.', true, '1 кг', true, 0),
  ('p-cucumber', 'ogurtsy-gladkie', 'Огурцы гладкие', 'market', 'cat-veg', null, 130, null, 'кг', 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=600&q=70', 'Свежие хрустящие огурцы. Доставка с местного рынка.', true, '1 кг', false, 1),
  ('p-potato', 'kartofel-belyy', 'Картофель белый', 'market', 'cat-veg', null, 55, null, 'кг', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=70', 'Картофель сорта «Белый». Подходит для жарки и пюре.', true, '1 кг', false, 2),
  ('p-onion', 'luk-repchatyy', 'Лук репчатый', 'market', 'cat-veg', null, 45, null, 'кг', 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?auto=format&fit=crop&w=600&q=70', 'Лук репчатый, средняя фракция.', true, '1 кг', false, 3),
  ('p-apple', 'yabloki-semerinka', 'Яблоки «Семеренко»', 'market', 'cat-veg', null, 110, null, 'кг', 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=600&q=70', 'Сочные кисло-сладкие яблоки сорта «Семеренко».', true, '1 кг', true, 4),
  ('p-banana', 'banany', 'Бананы', 'market', 'cat-veg', null, 95, null, 'кг', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=70', 'Спелые сладкие бананы.', true, '1 кг', false, 5),
  ('p-greens', 'zelen-pucok', 'Зелень (укроп/петрушка)', 'market', 'cat-veg', null, 40, null, 'пучок', 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=600&q=70', 'Свежая ароматная зелень. Цена за пучок.', true, '≈100 г', false, 6),
  ('p-watermelon', 'arbuz', 'Арбуз местный', 'market', 'cat-veg', null, 35, null, 'кг', 'https://images.unsplash.com/photo-1563114773-84221bd62daa?auto=format&fit=crop&w=600&q=70', 'Сладкий арбуз с дагестанских полей.', true, '≈8 кг', false, 7),
  ('p-beef', 'govyadina-vyrezka', 'Говядина (вырезка)', 'market', 'cat-meat', null, 780, null, 'кг', 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=600&q=70', 'Свежая говяжья вырезка от местных фермеров.', true, '1 кг', true, 8),
  ('p-lamb', 'baranina-zadnyaya', 'Баранина (задняя часть)', 'market', 'cat-meat', null, 650, null, 'кг', 'https://images.unsplash.com/photo-1630334337820-84afb05acf3a?auto=format&fit=crop&w=600&q=70', 'Молодая баранина для шашлыка и плова.', true, '1 кг', false, 9),
  ('p-chicken', 'kuritsa-domashnyaya', 'Курица домашняя', 'market', 'cat-meat', null, 420, null, 'кг', 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=70', 'Домашняя фермерская курица, потрошёная.', true, '≈1.8 кг', false, 10),
  ('p-mince', 'farsh-domashniy', 'Фарш домашний', 'market', 'cat-meat', null, 540, null, 'кг', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=70', 'Свежий фарш из говядины и баранины.', true, '1 кг', false, 11),
  ('p-trout', 'forel', 'Форель речная', 'market', 'cat-fish', null, 590, null, 'кг', 'https://images.unsplash.com/photo-1535007813616-79dc02ba4021?auto=format&fit=crop&w=600&q=70', 'Свежая речная форель, потрошёная.', true, '≈400 г', false, 12),
  ('p-salmon', 'losos-stejk', 'Лосось (стейк)', 'market', 'cat-fish', null, 1290, null, 'кг', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=70', 'Стейк из лосося охлаждённый.', true, '1 кг', false, 13),
  ('p-shrimp', 'krevetki', 'Креветки варёные', 'market', 'cat-fish', null, 690, null, 'уп', 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=70', 'Креветки варёно-мороженые, 500 г.', true, '500 г', false, 14),
  ('p-milk', 'moloko-domashnee', 'Молоко домашнее', 'market', 'cat-dairy', null, 95, null, 'л', 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=70', 'Натуральное цельное молоко от местных хозяйств.', true, '1 л', false, 15),
  ('p-tvorog', 'tvorog-domashniy', 'Творог домашний', 'market', 'cat-dairy', null, 280, null, 'кг', 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=70', 'Свежий жирный домашний творог.', true, '500 г', false, 16),
  ('p-eggs', 'yaytsa-domashnie', 'Яйца домашние', 'market', 'cat-dairy', null, 140, null, 'дес', 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=70', 'Домашние куриные яйца, 10 шт.', true, '10 шт.', false, 17),
  ('p-smetana', 'smetana', 'Сметана 25%', 'market', 'cat-dairy', null, 180, null, 'уп', 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=70', 'Натуральная сметана 25% жирности.', true, '400 г', false, 18),
  ('p-bread', 'khleb-belyy', 'Хлеб белый', 'market', 'cat-bakery', null, 50, null, 'шт', 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=70', 'Свежий белый хлеб, выпечка дня.', true, '500 г', false, 19),
  ('p-lavash', 'lavash-tonkiy', 'Лаваш тонкий', 'market', 'cat-bakery', null, 60, null, 'шт', 'https://images.unsplash.com/photo-1591985666643-1ecc67616216?auto=format&fit=crop&w=600&q=70', 'Тонкий армянский лаваш, свежевыпеченный.', true, '350 г', false, 20),
  ('p-chudu', 'chudu-s-myasom', 'Чуду с мясом', 'market', 'cat-bakery', null, 220, null, 'шт', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=70', 'Дагестанские чуду с домашним мясным фаршем.', true, '≈400 г', true, 21),
  ('p-syr-osetin', 'syr-osetinskiy', 'Сыр осетинский', 'market', 'cat-cheese', null, 540, null, 'кг', 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=70', 'Традиционный кавказский рассольный сыр.', true, '≈500 г', false, 22),
  ('p-kolbasa', 'kolbasa-domashnyaya', 'Колбаса домашняя', 'market', 'cat-cheese', null, 720, null, 'кг', 'https://images.unsplash.com/photo-1607434472257-d9f8e57a643d?auto=format&fit=crop&w=600&q=70', 'Домашняя сыровяленая колбаса.', true, '≈400 г', false, 23),
  ('p-rice', 'ris-krasnodarskiy', 'Рис «Краснодарский»', 'market', 'cat-bakaleya', null, 110, null, 'уп', 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=70', 'Круглозёрный краснодарский рис, 1 кг.', true, '1 кг', false, 24),
  ('p-grech', 'grechka', 'Гречка ядрица', 'market', 'cat-bakaleya', null, 130, null, 'уп', 'https://images.unsplash.com/photo-1545601445-4d6a0a0565f0?auto=format&fit=crop&w=600&q=70', 'Гречневая крупа ядрица, 900 г.', true, '900 г', false, 25),
  ('p-sugar', 'sahar', 'Сахар-песок', 'market', 'cat-bakaleya', null, 90, null, 'уп', 'https://images.unsplash.com/photo-1602634893456-d54178fa543a?auto=format&fit=crop&w=600&q=70', 'Сахар-песок белый, 1 кг.', true, '1 кг', false, 26),
  ('p-flour', 'muka', 'Мука пшеничная', 'market', 'cat-bakaleya', null, 95, null, 'уп', 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=70', 'Мука пшеничная высшего сорта, 2 кг.', true, '2 кг', false, 27),
  ('p-tea', 'chay-chernyy', 'Чай чёрный листовой', 'market', 'cat-tea', null, 320, null, 'уп', 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=70', 'Цейлонский чёрный листовой чай, 200 г.', true, '200 г', false, 28),
  ('p-coffee', 'kofe-zerno', 'Кофе в зёрнах', 'market', 'cat-tea', null, 890, null, 'уп', 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=70', 'Кофе арабика в зёрнах, обжарка средняя.', true, '1 кг', false, 29),
  ('p-pizza-margarita', 'pitstsa-margarita', 'Пицца «Маргарита»', 'food', 'cat-pizza', null, 490, null, 'шт', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=70', 'Классическая пицца с томатами, моцареллой и базиликом.', true, '30 см', true, 30),
  ('p-pizza-pepperoni', 'pitstsa-pepperoni', 'Пицца «Пепперони»', 'food', 'cat-pizza', null, 590, null, 'шт', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=70', 'Острая пицца с салями пепперони и моцареллой.', true, '30 см', false, 31),
  ('p-pizza-4cheese', 'pitstsa-4-syra', 'Пицца «4 сыра»', 'food', 'cat-pizza', null, 690, null, 'шт', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=70', 'Пицца с моцареллой, дорблю, пармезаном и чеддером.', true, '30 см', false, 32),
  ('p-burger-classic', 'burger-klassik', 'Бургер «Классик»', 'food', 'cat-burger', null, 310, null, 'шт', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=70', 'Сочный бургер с говяжьей котлетой, овощами и соусом.', true, '260 г', false, 33),
  ('p-burger-cheese', 'burger-chizburger', 'Чизбургер', 'food', 'cat-burger', null, 270, null, 'шт', 'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=600&q=70', 'Бургер с двойным чеддером и говяжьей котлетой.', true, '240 г', false, 34),
  ('p-shashlik-baranina', 'shashlyk-baranina', 'Шашлык из баранины', 'food', 'cat-shashlik', null, 580, null, 'порция', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=70', 'Сочный шашлык из молодой баранины с овощами и лавашом.', true, '300 г', true, 35),
  ('p-hinkal', 'khinkal-dagestanskiy', 'Хинкал по-дагестански', 'food', 'cat-shashlik', null, 420, null, 'порция', 'https://images.unsplash.com/photo-1606851094291-6efae152bb87?auto=format&fit=crop&w=600&q=70', 'Дагестанский хинкал с бараниной, бульоном и соусом.', true, '450 г', false, 36),
  ('p-roll-philadelphia', 'rolla-filadelfiya', 'Ролл «Филадельфия»', 'food', 'cat-sushi', null, 490, null, '8 шт', 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=70', 'Классический ролл с лососем и сливочным сыром.', true, '260 г', false, 37),
  ('p-roll-california', 'rolla-kaliforniya', 'Ролл «Калифорния»', 'food', 'cat-sushi', null, 450, null, '8 шт', 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=70', 'Ролл с крабом, авокадо, огурцом и икрой тобико.', true, '240 г', false, 38),
  ('p-soup-chicken', 'sup-kurinyy', 'Куриный суп с лапшой', 'food', 'cat-soup', null, 240, null, 'порция', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=70', 'Домашний куриный суп с лапшой и зеленью.', true, '350 мл', false, 39),
  ('p-salad-caesar', 'salat-tsezar', 'Салат «Цезарь» с курицей', 'food', 'cat-salad', null, 320, null, 'порция', 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=600&q=70', 'Салат с куриной грудкой, сухариками, пармезаном и соусом.', true, '220 г', false, 40),
  ('p-cola', 'cola', 'Кока-кола', 'food', 'cat-drinks', null, 95, null, '0.5 л', 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=600&q=70', 'Газированный напиток Coca-Cola, 0.5 л.', true, '500 мл', false, 41),
  ('p-mors', 'mors-klyukvennyy', 'Морс клюквенный', 'food', 'cat-drinks', null, 110, null, '0.5 л', 'https://images.unsplash.com/photo-1571687949921-1306bfb24b72?auto=format&fit=crop&w=600&q=70', 'Натуральный домашний клюквенный морс.', true, '500 мл', false, 42),
  ('p-tiramisu', 'tiramisu', 'Тирамису', 'food', 'cat-desserts', null, 210, null, 'порция', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=70', 'Классический итальянский десерт со сливочным маскарпоне.', true, '120 г', false, 43)
on conflict (id) do nothing;
